// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestaurantWebsite.Models;

#nullable disable

namespace RestaurantWebsite.Migrations
{
    [DbContext(typeof(FoodContext))]
    [Migration("20230213202246_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("RestaurantWebsite.Models.Food", b =>
                {
                    b.Property<int>("MenuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Price")
                        .HasColumnType("REAL");

                    b.HasKey("MenuId");

                    b.ToTable("Foods");

                    b.HasData(
                        new
                        {
                            MenuId = 1,
                            Name = "Plain Pizza",
                            Price = 10.0
                        },
                        new
                        {
                            MenuId = 2,
                            Name = "Neopolitan Pizza",
                            Price = 13.449999999999999
                        },
                        new
                        {
                            MenuId = 3,
                            Name = "White Pizza",
                            Price = 11.0
                        },
                        new
                        {
                            MenuId = 4,
                            Name = "Philly Pizza",
                            Price = 14.449999999999999
                        },
                        new
                        {
                            MenuId = 5,
                            Name = "House Special Pizza",
                            Price = 15.0
                        },
                        new
                        {
                            MenuId = 6,
                            Name = "Meat Lovers Pizza",
                            Price = 13.449999999999999
                        });
                });

            modelBuilder.Entity("RestaurantWebsite.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Fname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Lname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("People")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReserveDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReserveTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Reservations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "AnaMarie@gmail.com",
                            Fname = "Ana",
                            Lname = "Marie",
                            Note = "n/a",
                            People = 5,
                            PhoneNumber = "215-123-4567",
                            ReserveDate = new DateTime(2020, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReserveTime = "6:30 PM"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
