// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestaurantWebsite.Models;

#nullable disable

namespace RestaurantWebsite.Migrations
{
    [DbContext(typeof(FoodContext))]
    [Migration("20230211042244_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("RestaurantWebsite.Models.Food", b =>
                {
                    b.Property<int>("MenuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Price")
                        .HasColumnType("REAL");

                    b.HasKey("MenuId");

                    b.ToTable("Foods");

                    b.HasData(
                        new
                        {
                            MenuId = 1,
                            Name = "Plain Pizza",
                            Price = 10.0
                        },
                        new
                        {
                            MenuId = 2,
                            Name = "Neopolitan Pizza",
                            Price = 13.449999999999999
                        },
                        new
                        {
                            MenuId = 3,
                            Name = "White Pizza",
                            Price = 11.0
                        },
                        new
                        {
                            MenuId = 4,
                            Name = "Philly Pizza",
                            Price = 14.449999999999999
                        },
                        new
                        {
                            MenuId = 5,
                            Name = "House Special Pizza",
                            Price = 15.0
                        },
                        new
                        {
                            MenuId = 6,
                            Name = "Meat Lovers Pizza",
                            Price = 13.449999999999999
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
