// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestaurantWebsite.Models;

#nullable disable

namespace RestaurantWebsite.Migrations
{
    [DbContext(typeof(RestaurantContext))]
    partial class RestaurantContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("RestaurantWebsite.Models.Food", b =>
                {
                    b.Property<int>("FoodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Price")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("FoodId");

                    b.ToTable("Foods");

                    b.HasData(
                        new
                        {
                            FoodId = 1,
                            Description = "Homemade pizza sauce, Mozzarella cheese, Parmesan cheese",
                            Name = "Plain Pizza",
                            Price = 10m
                        },
                        new
                        {
                            FoodId = 2,
                            Description = "Pepperoni, Tomatoes, Paprika, Chili, Mozzarella, Parmesan",
                            Name = "Pepperoni Pizza",
                            Price = 14.99m
                        },
                        new
                        {
                            FoodId = 3,
                            Description = "Salami, Olives, Bell pepper, Mushrooms, Mozzarella, Parmesan",
                            Name = "Pizza with Salami and Olives",
                            Price = 15.99m
                        },
                        new
                        {
                            FoodId = 4,
                            Description = "Broccoli, Mushrooms, Bell pepper, Corn, Onion, Mozzarella, Parmesan",
                            Name = "Veggie Pizza",
                            Price = 14.99m
                        },
                        new
                        {
                            FoodId = 5,
                            Description = "Mozzarella, Parmesan, Basil, Fresh tomatoes, Tomato sauce",
                            Name = "Margherita Pizza",
                            Price = 10.99m
                        },
                        new
                        {
                            FoodId = 6,
                            Description = "Minced meat, Bacon, Jalapeño, Mozzarella, Parmesan, Olives, Tomatoes",
                            Name = "Pizza with Minced Meat",
                            Price = 15.99m
                        },
                        new
                        {
                            FoodId = 7,
                            Description = "Salami, Chilli, Jalapeño, Mozzarella, Parmesan, Tomato sauce",
                            Name = "Hot Salami Pizza",
                            Price = 14.99m
                        },
                        new
                        {
                            FoodId = 8,
                            Description = "Grilled meat, Tomatoes, Bell pepper, Onion, Mozzarella, Parmesan",
                            Name = "Pizza with Grilled Meat",
                            Price = 16.99m
                        });
                });

            modelBuilder.Entity("RestaurantWebsite.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Fname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Lname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("People")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReserveDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReserveTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Reservations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "ithan@gmail.com",
                            Fname = "Ithan",
                            Lname = "Sandoval",
                            Note = "n/a",
                            People = 5,
                            PhoneNumber = "215-123-4567",
                            ReserveDate = new DateTime(2023, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReserveTime = "6:30 PM"
                        },
                        new
                        {
                            Id = 2,
                            Email = "Peter@gmail.com",
                            Fname = "Peter",
                            Lname = "Hoang",
                            Note = "n/a",
                            People = 4,
                            PhoneNumber = "267-999-999",
                            ReserveDate = new DateTime(2023, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReserveTime = "7:30 PM"
                        },
                        new
                        {
                            Id = 3,
                            Email = "Kevin@gmail.com",
                            Fname = "Kevin",
                            Lname = "Nguyen",
                            Note = "n/a",
                            People = 4,
                            PhoneNumber = "610-123-4567",
                            ReserveDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReserveTime = "5:30 PM"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
